220314_WebProject/WebTeamProject/corona_19/urls.py
# Root URLConf(http://127.0.0.1:8000/)
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),  # Home Page
    path('admin/', admin.site.urls),                                          # Admin Page
    path('main/', include('main.urls')),                                      # login 후 Home Page
    path('users/', include('users.urls')),                                    # login, 회원가입 page
    path('maps/', include('maps.urls')),                                      # 병원 map page
    path('bbs/', include('probbs.urls')),                                     # 전문의 게시판 page
    path('guide/', include('guide.urls')),                                    # Guide Page(코로나 증상 및 예방 조치)
    path('diagnosis/', include('diagnosis.urls')),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

220314_WebProject/WebTeamProject/main/urls.py
# Main URLConf(http://127.0.0.1:8000/main)
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    # path('list/', views.b_list, name='b_list'),
]

220314_WebProject/WebTeamProject/probbs/urls.py
from django.urls import path
from django.conf import settings
from probbs import views

app_name = 'probbs'
urlpatterns = [
    path('', views.index, name='index'),
    path('question/create/', views.question_create, name='question_create'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/comment/create/', views.create_comment, name='create_comment'),
    path('<int:question_id>/comment/delete/', views.delete_comment, name='delete_comment'),
    path('<int:question_id>/question/modify/', views.modify_question, name='modify_question'),
    path('<int:question_id>/question/delete/', views.delete_question, name='delete_question'),
    path('<int:question_id>/question/like/', views.like_question, name='like_question')

]

220314_WebProject/WebTeamProject/probbs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime, timedelta


# Create your models here.

class Question(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=1, related_name='author_question')
    content = models.TextField()
    views = models.PositiveIntegerField(default=0)
    create_date = models.DateTimeField(auto_now_add=True)
    comments = models.PositiveIntegerField(null=True)
    question_like_count = models.ManyToManyField(User, related_name='like_question')

    class Meta:
        permissions = [
            ('can_create_doctor', 'Can Create a Doctor')
        ]

    def __str__(self):
        return self.title

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.create_date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.create_date.date()
            return str(time.days) + '일 전'
        else:
            return False


class Comment(models.Model):
    post = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=1)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.content

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.create_date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.create_date.date()
            return str(time.days) + '일 전'
        else:
            return False

220314_WebProject/WebTeamProject/probbs/forms.py
from django import forms
from probbs.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }

220314_WebProject/WebTeamProject/probbs/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from probbs.models import Question, Comment
from django.contrib import messages
from probbs.forms import QuestionForm
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.db.models import Q


# Create your views here.


def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')

    question = Question.objects.order_by('-create_date')
    if kw:
        question = question.filter(
            Q(title__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw)
        ).distinct()
    paginator = Paginator(question, 10)
    page_obj = paginator.get_page(page)
    context = {
        'question_list': page_obj,
        'page': page,
        'kw': kw
    }
    return render(request, 'probbs/bbs_main.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    comment = Comment.objects.filter(post=question_id).order_by('-create_date')
    comment_count = comment.exclude(deleted=True).count()

    question.views += 1
    question.save()

    if request.user == question.author:
        question_auth = True
    else:
        question_auth = False

    context = {
        'question': question,
        'question_auth': question_auth,
        'comment_count': comment_count,
        'comments': comment,
    }
    return render(request, 'probbs/bbs_detail.html', context)


@login_required(login_url='users:login')
@permission_required('can_create_doctor', login_url=reverse_lazy('probbs:index'))
def create_comment(request, question_id):
    post = get_object_or_404(Question, id=question_id)
    author = request.POST.get('author')
    content = request.POST.get('content')
    if content:
        comment = Comment.objects.create(post=post, content=content, author=request.user)
        comment_count = Comment.objects.filter(post=question_id).exclude(deleted=True).count()
        post.comments = comment_count
        post.save()
        data = {
            'author': author,
            'content': content,
            'created': '방금 전',
            'comment_count': comment_count,
            'comment_id': comment.id
        }
        if request.user == post.author:
            data['self_comment'] = '(작성자)'

        return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type="application/json")


@login_required(login_url='users:login')
def delete_comment(request, question_id):
    post = get_object_or_404(Question, id=question_id)
    comment_id = request.POST.get('comment_id')
    target_comment = Comment.objects.get(pk=comment_id)

    if request.user == target_comment.author:
        target_comment.deleted = True
        target_comment.save()
        comment_count = Comment.objects.filter(post=question_id).exclude(deleted=True).count()
        post.comments = comment_count
        post.save()
        data = {
            'comment_id': comment_id,
            'comment_count': comment_count,
        }
        return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type='application/json')


@login_required(login_url='users:login')
# @permission_required('can_create_doctor', login_url=reverse_lazy('probbs:index'))
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            return redirect('probbs:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'probbs/bbs_form.html', context)


@login_required(login_url='users:login')
def modify_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('probbs:detail')

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.save()
            return redirect('probbs:detail', question_id=question.id)
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'probbs/bbs_form.html', context)


@login_required(login_url='users:login')
def delete_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('probbs:detail', question_id=question.id)
    question.delete()
    return redirect('probbs:index')


@login_required(login_url='users:login')
def like_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.question_like_count.add(request.user)
    return redirect('probbs:detail', question_id=question.id)

220314_WebProject/WebTeamProject/probbs/templates/probbs/bbs_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block html_header %}

<meta name="viewport" content="width=800, user-scalable=yes">
<link rel="stylesheet" href="/static/probbs/css/style.css">
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

<script type="text/javascript">
$(document).ready(function (){
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri')
        }
    })

    $('#comment_author').click(function (){
        var content = $('#content_id').val()
        var author = $('#comment_author').val()

        $.ajax({
            async: true,
            type: "POST",
            url: "{% url 'probbs:create_comment' question.id %}",
            dataType: "json",
            data: {
                'author': author,
                'content': content,
                'csrfmiddlewaretoken': '{{csrf_token}}',
            },
            success: function (response) {
                if (response.self_comment){
                    $('#comment_list').append(
                       '<div><div id='+response.comment_id+'><strong style="margin-left: 20px;">'+response.author+'&nbsp;<span>'+response.self_comment+'</span></strong>'+
                       '<span style="float:right;">'+response.created+'</span>'+
                       '<div><div style="white-space:pre-wrap; text-align:left; margin-left: 50px; margin-top: 10px;">'+response.content+
                       '</div><div style="text-align:right;"><a onclick="comment_delete('+response.comment_id+')">댓글삭제</a></div></div><hr></div><div class='+response.comment_id+'></div>'
                     )
                }
                else{
                    $('#comment_list').append(
                        '<div><div id='+response.comment_id+'><strong style="margin-left: 20px;">'+response.author+'</strong>'+
                        '<span style="float:right;">'+response.created+'</span>'+
                        '<div><div style="white-space:pre-wrap; text-align:left; margin-left: 50px; margin-top: 10px;">'+response.content+
                        '</div><div style="text-align:right;"><a onclick="comment_delete('+response.comment_id+')">댓글삭제</a></div></div><hr></div><div class='+response.comment_id+'></div>'
                    )
                }
                $('#content_id').val("")
             },
             error: function () {
                    if ($('#content_id').val()=="") {
                        alert('댓글을 입력해주세요.')
                    }
             },
        })
    })
})

$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});

</script>
{% endblock %}

{% block html_body %}
<br><br><br>
<div class="container">
    <div class="row-mt-5">
        <div class="col-12">
            <!--본문-->
            <div class="card" style="width: 100%;">
                <!--제목,분류,작성일-->
                <div class="card-header shadow-lg p-2 mb-1 bg-opacity-25 rounded">
                    <div style="margin: 0px; margin-top: 8px; font-size: 22px;"><strong>{{ question.title }}</strong>&nbsp;&nbsp;</div>
                    <span style="float:right;">{{ question.create_date|date:'Y.m.d. H:i' }}</span>
                </div>
                <div class="card-body" style="min-height: 350px; color:black;">
                    <!--작성자, 조회수-->
                    <div>
                        <span><i class="fas fa-user-edit"></i>&nbsp;작성자 : {{ question.author }}</span>
                        <span style="float: right;">조회수 : {{ question.views }}</span>
                    </div>
                    <br><br>
                    <!--내용-->
                    <div >
                        {{ question.content | linebreaksbr }}
                    </div>
                </div>
                {% if request.user == question.author %}

                {% endif %}
                <div class="row my-3">
                    <div > <!-- 추천영역 -->
                         {% if request.user == question.author %}
                            <a href="{% url 'probbs:modify_question' question.id  %}"
                               class="btn btn-sm btn-outline-secondary" style="position: relative; left: 1%; top: 78%">수정</a>
                            <a href="{% url 'probbs:delete_question' question.id  %}"
                               class="btn btn-sm btn-outline-secondary" style="position: relative; left: 1%;top: 78%">삭제</a>
                        {% endif %}
{#                        <div class="my-1">#}
                        <div class=" p-3  font-weight-bolder "
                             style="position: relative; left: 93.5%; ">{{question.question_like_count.count}}</div>
                        <a href="#" data-uri="{% url 'probbs:like_question' question.id  %}"
                           class="recommend btn btn-sm btn-block my-1"
                           style="position: relative; left: 92%; background-color: #d14040f2;
                           color: white; font-size: 11px;">추천</a>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <!-- 댓글 -->
            <div class="card" style="width: 100%;">
                <div class="card-header">
                    {% csrf_token %}
                    <div class="card-group row">
                        <textarea class="form-control" id="content_id" rows="3"
                                  placeholder="댓글을 입력하세요." style="margin-top: 6px;"></textarea>
                    </div>
                    <div class="text-right" style="float: right">
                        <a href="{% url 'probbs:index' %}" class="btn btn-sm"
                                style="background-color: grey; color: white; font-size: 15px;
                                margin-top: 8px; margin-right: 924.5px;">목록으로</a>
                        <button id="comment_author" class="btn btn-sm"
                                style="background-color: #d14040f2; color: white; font-size: 15px;
                                margin-top: 8px; margin-right: -10px;">댓글달기</button>
                    </div>
                </div>
                <br>
                {% if comments %}
                <div id="hide_more_button"><strong><a id=hide_button_count style="color:black;">&nbsp;댓글 접기 &middot;&nbsp;{{ comment_count }}개의 댓글<br></a></strong></div>
                <div id="show_more_button" style="display:none;"><strong><a id=show_button_count style="color:black;">&nbsp;댓글 펼치기 &middot;&nbsp;{{ comment_count }}개의 댓글<br></a></strong></div>
                {% else %}
                <div id="hide_more_button"><strong><a id=hide_button_count style="color:black;"><br></a></strong></div>
                <div id="show_more_button" style="display:none;"><strong><a id=show_button_count style="color:black;"><br></a></strong></div>
                {% endif %}
                <hr>
                <div id="more_comment">
                    {% if comments %}
                        {% for comment in comments %} <!-- ? -->
                        <div id="{{ comment.id }}">
                            {% if comment.deleted %}
                            <span>삭제된 댓글입니다.</span><hr>
                            {% else %}
                                {% if comment.author == question.author %}
                                 <strong style="margin-left: 20px;">{{ comment.author }}&nbsp;<span style="color:gray";>(작성자)</span></strong>
                                {% else %}
                                 <div style="margin-left: 15px;"><strong>{{ comment.author }}</strong></div>
                                {% endif %}
                                {% if comment.created_string == False %}
                                <span style="float: right">{{ comment.create_date|date:'m월 d일' }}</span>
                                {% else %}
                                <span style="float:right; color:gray;">{{ comment.created_string }}</span>
                                {% endif %}
                                {% if comment.author == request.user %}
                                <div>
                                    <div style="white-space: pre-line; text-align: left;
                                     margin-left: 50px; margin-top: 10px;">{{ comment.content }}</div>
                                    <div style="text-align: right;">
                                        <a onclick="comment_delete('{{ comment.id }}')">댓글삭제</a>
                                    </div>
                                </div>
                                <hr>
                                {% else %}
                                <div>
                                    <div style="white-space: pre-wrap; text-align: left;">{{ comment.content }}</div>
                                </div>
                                <hr>
                                {% endif %}
                            {% endif %}
                        </div>
                        <div class="{{ comment.id }}"></div>
                        {% endfor %}
                    {% endif %}
                    <input type="hidden" id="comment_author" value={{ request.user }}>
                    <div id="comment_list"></div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>





<script type="text/javascript">
function comment_delete(value) {
    var comment_id = value
    var delete_warning = confirm('댓글을 삭제하시겠습니까?')
    if (delete_warning === true) {
        $.ajax({
            async: true,
            type: "POST",
            url: "{% url 'probbs:delete_comment' question.id %}",
            dataType: "json",
            data: {
                'comment_id': comment_id,
                'csrfmiddlewaretoken': '{{csrf_token}}',
            },
            success: function (response) {
                $('#'+response.comment_id).replaceWith('<span style="color:gray;">삭제된 댓글입니다.</span><hr>')
            },
            error: function (request,status,error) {
                alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
            }
        })
    }
}

$('#hide_more_button').click(function(){
    $('#more_comment').hide();
    $('#show_more_button').show();
    $('#hide_more_button').hide();
});
$('#show_more_button').click(function(){
    $('#more_comment').show();
    $('#show_more_button').hide();
    $('#hide_more_button').show();
});
</script>
{% endblock %}

220314_WebProject/WebTeamProject/probbs/templates/probbs/bbs_form.html
{% extends 'base.html' %}

{% block html_header %}
{% endblock %}

{% block html_body %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2" style="font-weight: bold; font-size: 18px;">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="title" style="font-weight: normal;margin-bottom: 3px; font-size: 18px;">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="form-group" style="margin-top: 20px" >
            <label for="content" style="font-weight: normal;margin-bottom: 3px; font-size: 18px; ">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="form-control" style="background-color: #d14040f2;">저장하기</button>
    </form>
</div>

{% endblock %}

220314_WebProject/WebTeamProject/probbs/templates/probbs/bbs_main.html
{% extends 'base.html' %}

{% block html_header %}
<link rel="stylesheet" href="/static/probbs/css/style.css">
<script src="/static/probbs/js/btn_functions.js"></script>
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"))
        $("#searchForm").submit()
    })

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val())
        $("#page").val(1)
        $("#searchForm").submit()
    })
})
</script>
{% endblock %}

{% block html_body %}

<section class="notice">
<div class="page-title">
    <div class="container">
        <h3>전문의에게 물어보세요</h3>
    </div>
</div>

<!-- board seach area -->

<!-- board list area -->
<div id="board-list">
    <div class="container">
        <table class="board-table">
            <thead>
            <tr>
                <th scope="col" class="th-num">번호</th>
                <th scope="col" class="th-title">제목</th>
                <th scope="col" class="th-date">작성자</th>
                <th scope="col" class="th-date">등록일</th>
                <th scope="col" class="th-date">조회수</th>
            </tr>
            </thead>
            <tbody>
            {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td>{{ question.id }}</td>
                <td style="text-align: left; padding: 15px;"><a href="{% url 'probbs:detail' question.id %}">{{ question.title|truncatechars:30 }}</a>
                    {% if question.comments %}
                    <span style="color: red">&nbsp;[{{ question.comments }}]</span>
                    {% endif %}
                </td>
                <td>{{ question.author.username }}</td>
                {% if question.created_string == False %}
                <td>{{ question.create_date|date:'m월 d일' }}</td>
                {% else %}
                <td>{{ question.created_string }}</td>
                {% endif %}
                <td>{{ question.views }}</td>
            </tr>
            {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>

</div>
<div id="board-search">
    <div class="container">
        <div class="search-window" style="background-color: white;">
            <div>
                <a href="{% url 'probbs:question_create' %}" class="btn btn-sm">글쓰기</a>
                <a href="{% url 'home' %}" class="btn btn-sm" style="margin-left: 67%; background-color: grey; color: white">메인으로 돌아가기</a>

            </div>

                <div class="search-wrap">
                    <label for="search" class="blind">공지사항 내용 검색</label>
                    <input id="search" type="text" class="form-control kw" placeholder="검색어를 입력해주세요." value="{{ kw|default_if_none:'' }}">
                    <button type="button" class="btn btn-dark" id="btn_search">검색</button>
                </div>

        </div>
    </div>
</div>
</section>
    <ul class="pagination justify-content-center" style="padding: 50px;">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="#">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">&laquo;</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-3 and page_number <= question_list.number|add:3 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}" href="#">&raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">&raquo;</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <form id="searchForm" method="get" action="{% url 'probbs:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}