220314_WebProject/WebTeamProject/corona_19/urls.py
# Root URLConf(http://127.0.0.1:8000/)
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),  # Home Page
    path('admin/', admin.site.urls),                                          # Admin Page
    path('main/', include('main.urls')),                                      # login 후 Home Page
    path('users/', include('users.urls')),                                    # login, 회원가입 page
    path('maps/', include('maps.urls')),                                      # 병원 map page
    path('bbs/', include('probbs.urls')),                                     # 전문의 게시판 page
    path('guide/', include('guide.urls')),                                    # Guide Page(코로나 증상 및 예방 조치)
    path('diagnosis/', include('diagnosis.urls')),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

220314_WebProject/WebTeamProject/main/urls.py
# Main URLConf(http://127.0.0.1:8000/main)
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    # path('list/', views.b_list, name='b_list'),
]

220314_WebProject/WebTeamProject/users/urls.py
# Users URLConf(http://127.0.0.1:8000/users)
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('account/', views.account, name='account'),
]

220314_WebProject/WebTeamProject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as django_logout, \
    login as django_login, authenticate
from django.contrib import auth
from django.contrib.auth.models import User
from django.http import HttpResponse


def login(request):
    if request.method == 'POST':
        user_name = request.POST['user_name']
        password = request.POST['password']
        user = authenticate(request, username=user_name, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            return render(request, 'users/login.html',)
    else:
        return render(request, 'users/login.html')

def logout(request):
    django_logout(request)
    return redirect('home')


def account(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                username=request.POST['user_name'],
                password=request.POST['password1'],
                email=request.POST['email'], )
            auth.login(request, user)
            return redirect('/')
        return render(request, 'users/account.html')
    return render(request, 'users/account.html')

220314_WebProject/WebTeamProject/users/templates/users/account.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sign Up Form</title>
        <link rel="stylesheet" href="https://codepen.io/gymratpacks/pen/VKzBEp#0">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="/static/users/css/account.css">
    </head>
    <body>
      <div class="row">
    <div class="col-md-12">
        <br><br><br><br>
      <form action="{% url 'users:account' %}" method="post">
          {% csrf_token %}
        <h1> Sign Up </h1>

        <fieldset>

          <label for="name">ID:</label>
          <input type="text" id="name" name="user_name">

          <label for="email">Email:</label>
          <input type="email" id="email" name="email">

          <label for="password">Password:</label>
          <input type="password" id="password1"  name="password1">

          <label for="password2">Password Check:</label>
          <input type="password" id="password2"  name="password2">

        </fieldset>

        <button type="submit">Sign Up</button>

       </form>
        </div>
      </div>

    </body>
</html>

220314_WebProject/WebTeamProject/users/templates/users/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block html_header %}
    <link href="/static/users/css/login.css" rel="stylesheet">

    <style type="text/css">
     a:link { color: #c71d44; text-decoration: none;}
     a:visited { color: #c71d44; text-decoration: none;}
     a:hover { color: #006DD7; text-decoration: underline;}
    </style>


{% endblock %}


{% block html_body %}

<br><br><br><br>
<div class="login">
  <div class="login-triangle"></div>

  <h2 class="login-header">로그인</h2>

  <form method="POST" class="login-form">
    {% csrf_token %}
    <p><input name="user_name" type="text" placeholder="ID"></p>
    <p><input name="password" type="password" placeholder="Password"></p>
    <p><input type="submit" value="Log In"></p>
      <a href="{% url 'users:account' %}">Create a new Account</a>
  </form>
</div>


{% endblock %}