220314_performance_evaluation/config/urls.py
# Root URLConf(http://127.0.0.1:8000/)
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),  # Home Page
    path('home/', TemplateView.as_view(template_name='index2.html'), name='home2'),  # Home Page
    path('admin/', admin.site.urls),                                          # Admin Page
    path('main/', include('main.urls'),),                                      # login 후 Home Page
    path('users/', include('users.urls')),                                    # login, 회원가입 page                                     # 병원 map page
    path('probbs/', include('probbs.urls')),                                     # 전문의 게시판 page
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

220314_performance_evaluation/main/urls.py
# Main URLConf(http://127.0.0.1:8000/main)
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    # path('list/', views.b_list, name='b_list'),
]

220314_performance_evaluation/probbs/urls.py
from django.urls import path
from django.conf import settings
from probbs import views

app_name = 'probbs'
urlpatterns = [
    path('', views.index, name='index'),
    path('question/create/', views.question_create, name='question_create'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/comment/create/', views.create_comment, name='create_comment'),
    path('<int:question_id>/comment/delete/', views.delete_comment, name='delete_comment'),
    path('<int:question_id>/question/modify/', views.modify_question, name='modify_question'),
    path('<int:question_id>/question/delete/', views.delete_question, name='delete_question'),
    path('<int:question_id>/question/like/', views.like_question, name='like_question')

]

220314_performance_evaluation/users/urls.py
# Users URLConf(http://127.0.0.1:8000/users)
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('account/', views.account, name='account'),
]

220314_performance_evaluation/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>수행평가</title>

    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

    <!-- Bootstrap CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="icon" type="image/png" sizes="64x64" href="/static/img/dog.jpg">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@5.14.0/css/all.min.css">
    <link rel="stylesheet" href="/static/main/css/co_common.css">

    <script src="/static/main/js/jquery-1.11.2.min.js"></script>



<script>
function link_url(link_url) {
    document.location.href = link_url;
}
</script>
{% block html_header %}

{% endblock %}
</head>

<body>
     <!-- Navigation -->


    <div class="navigation t_dp_n m_dp_n">
        <div>
            <div class="n_left"><h1 class="corona_h1"><a href="/home">수행평가<span></span></a></h1></div>
            <br><br>
            <div class="n_right">
                <ul class="nino-iconsGroup nav navbar-nav">
                    {% if user.is_authenticated %}
                        <li><a href="#" onclick="link_url('{% url 'users:logout' %}')">
                            <i class="mdi fas fa-user-slash nino-icon"></i></a></li>
                    {% else %}
                        <li><a href="#" onclick="link_url('{% url 'users:login' %}')">
                            <i class="mdi far fa-user nino-icon"></i>
                        </a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>


    <br>
    <!-- // Navigation -->
    <!-- Header -->

{% block html_body %}

{% endblock %}

</body>
</html>

220314_performance_evaluation/templates/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block html_header %}


<style>
@import url(https://fonts.googleapis.com/css?family=Pacifico);

@import "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css";
#container {
  min-width: 100%;
  max-width: 100%;
  margin: 0 auto;
  margin-top: 40px;
}

#outer-container {
  max-width: 100%;
  min-width: 100%;
  margin: 0 auto;
}

#outer-container .controls {
  display: table;
  margin: 0 auto;

}

#outer-container button {
    margin: 0 auto;
    margin-bottom: 40px;
    color: #fff;
    background-color: #007bff;
    border-color: #007bff;
    border: 1px solid transparent;
    padding: .375rem 31.75rem;
    font-size: 1rem;
    line-height: 1.5;
    border-radius: .25rem;
}
#parentContainer {
  min-width: 320px;
  max-width: 800px;
}

#play-controls {
  position: absolute;
  left: 100px;
  top: 350px;
}

#play-pause-button {
  width: 30px;
  height: 30px;
  cursor: pointer;
  border: 1px solid silver;
  border-radius: 3px;
  background: #f8f8f8;

}

#play-range {
  transform: translateY(2.5px);
}


</style>




{% endblock %}



{% block html_body %}

      <main class="px-3">
    <br><br><br><br><br><br><br><br><br><br>
          <center><h1><p style="font-size: 30px" style="background-color:#800F0F;" class="lead">
        {% if request.user.is_authenticated %}
        {{ request.user.username }} 님 환영합니다.
        {% else %}
        로그인이 필요합니다.
        {%  endif %}
    </p></h1></center>
  </main>

{% endblock %}

220314_performance_evaluation/templates/index2.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block html_header %}


<style>
@import url(https://fonts.googleapis.com/css?family=Pacifico);

@import "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css";
#container {
  min-width: 100%;
  max-width: 100%;
  margin: 0 auto;
  margin-top: 40px;
}

#outer-container {
  max-width: 100%;
  min-width: 100%;
  margin: 0 auto;
}

#outer-container .controls {
  display: table;
  margin: 0 auto;

}

#outer-container button {
    margin: 0 auto;
    margin-bottom: 40px;
    color: #fff;
    background-color: #007bff;
    border-color: #007bff;
    border: 1px solid transparent;
    padding: .375rem 31.75rem;
    font-size: 1rem;
    line-height: 1.5;
    border-radius: .25rem;
}
#parentContainer {
  min-width: 320px;
  max-width: 800px;
}

#play-controls {
  position: absolute;
  left: 100px;
  top: 350px;
}

#play-pause-button {
  width: 30px;
  height: 30px;
  cursor: pointer;
  border: 1px solid silver;
  border-radius: 3px;
  background: #f8f8f8;

}

#play-range {
  transform: translateY(2.5px);
}

{#html{#}
{#  background:#f8f8f8;#}

{##}
{#body{#}
{#  width:295px;#}
{#  height:210px;#}
{#  margin:25px auto;#}
{#  position:relative;#}

{##}
{#p{#}
{#  font-family: 'Pacifico', cursive;#}
{#  color:#ffffff;#}
{#  font-weight:400;#}
{#  font-size:100px;#}
{#  text-align:center;#}
{#  width:295px;#}
{#  position:absolute;#}
{#  bottom:-140px;#}

</style>




{% endblock %}

{% block html_body %}


        <div class="header">
        <div>
            <br><br>
                <div id="gnb" class="gnb t_dp_n m_dp_n">
                    <ul>
                        <li><a href={% url 'probbs:index' %}>게시판</a>
                        </li>
                    </ul>
                                <br><br>
                </div>
            </div>
        </div>


      <main class="px-3">
    <br><br><br><br><br><br>
          <center><h1><p style="font-size: 30px" style="background-color:#F13DE1;" class="lead">
        {% if request.user.is_authenticated %}
        {{ request.user.username }} 님 환영합니다.
        {% else %}
        로그인이 필요합니다.
        {%  endif %}
          <br><br><br><br><br>
    </p></h1></center>
  </main>


      <center><img src="/static/img/dog2.jpg"  width="1000"></center>

{% endblock %}